### ISSUE TITLE
Syntax highlighting for python

### ISSUE THREAD

**Issue by Michael0x18** [Michael0x18/CEdit#3]
Python syntax highlighting in the editor

**Comment by HexCodeFFF** [comment]
I'd see if you can find a [syntax highlighting library written in C](https://stackoverflow.com/questions/4165449/syntax-highlighting-library-written-in-c-c), and then rework it to output to whatever text renderer your program uses

**Comment by Michael0x18** [comment]
The trouble is most of those are too heavy and/or dependent on having a complete set of libraries to go along with it.
Remember, on the CE, programs are very limited in size (think counting kilobytes and even sometimes individual bytes) and so many of those libraries won't work.
I'll probably focus on writing some assembly library for that once I'm done rewriting the core (see the cedit2 branch)
